### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by LucasWBritz** [etrupja/DrinkAndGo#1] opened 2018-02-28 01:25 UTC
Hi! There is an incorrect '}' at the end of MockCategoryRepository.cs. 
You need to remove it to be able to compile and run the application. :)

**Comment by etrupja** [comment] 2018-03-29 15:38
@LucasWBritz thanks a lot for creating this issue. 
The issue is now fixed

**Comment by etrupja** [comment] 2018-03-29 15:38
@LucasWBritz sorry for the late response.

**Closed as completed by etrupja** 2018-03-29 15:38 UTC
Labels: wontfix
